name: Github Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [ push ]
jobs:
  build-and-publish:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: auth
        name: Authenticate to Google Cloud
        # Workload Identityé€£æºã‚’åˆ©ç”¨ã—ã¦GitHub Actionsã‹ã‚‰Google Cloudã¸èªè¨¼ã‚’è¡Œã†
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        # gcloudã‚³ãƒãƒ³ãƒ‰ã‚’å®Ÿè¡Œã™ã‚‹ãŸã‚ã«Cloud SDKã‚’æº–å‚™ã™ã‚‹
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info